version: '3.4'

services:
  ptrampert.apiproxy.sampleapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ./PTrampert.ApiProxy.SampleApp/sample-app/build/:/app/wwwroot/

  ptrampert.apiproxy.sampleapp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

