# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet library

env:
  VERSION_FORMAT: ${{'${major}.${minor}.${patch}'}}

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]
jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set Prerelease Pattern
      run: |
        echo "PRERELEASE_PATTERN=-${GITHUB_HEAD_REF:=$GITHUB_REF_NAME}-\${increment}" >> $GITHUB_ENV
      if: ${{env.GITHUB_REF_NAME != 'master'}}
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Calculate Version
      id: versioning
      uses: paulhatch/semantic-version@v5.0.0-beta
      with:
        version_format: ${{format('{0}{1}', env.VERSION_FORMAT, env.PRERELEASE_PATTERN)}}
        
    - name: Restore dependencies
      run: dotnet restore PTrampert.ApiProxy.sln
      
    - name: Test
      run: dotnet test PTrampert.ApiProxy.Test/PTrampert.ApiProxy.Test.csproj
      
    - name: Pack
      run: dotnet pack PTrampert.ApiProxy/PTrampert.ApiProxy.csproj -c Release -o package --include-source /p:Version=$VERSION
      env:
        VERSION: ${{steps.versioning.outputs.version}}
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: |
          package/*.nupkg
          package/*.snupkg
