# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Calculate Version
      uses: paulhatch/semantic-version@v4.0.3
    - name: Restore dependencies
      run: dotnet restore PTrampert.ApiProxy.sln
    - name: Test
      run: dotnet test PTrampert.ApiProxy.Test/PTrampert.ApiProxy.Test.csproj
    - name: Pack
      run: dotnet pack PTrampert.ApiProxy/PTrampert.ApiProxy.csproj -c Release --include-source /p:Version=$version
      env:
        version: $version
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: "**/*.s?nupkg"
