name: Build and Test PR
on:
  pull_request:
    branches: ["dev"]
jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      main_branch: 'refs/heads/master'
  build-test:
    uses: ./.github/workflows/build-test-dotnet.yml
    needs: version
    with:
      project_name: PTrampert.ApiProxy
      version: ${{needs.version.outputs.version}}